server:
    port: 8888

spring:
  application:
    name: config-Server

  profiles:
    active: native
    

  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/configurations
            - classpath:/configurations/platform
            - classpath:/configurations/services