server:
    port: 8888

spring:
  application:
    name: config-Server


    

  cloud:
    config:
      server:
        git:
          uri: https://github.com/MaheshaDinu/cloud-native-e-library-configurations.git
          search-paths: platform,services
        native:
          search-locations:
            - classpath:/configurations
            - classpath:/configurations/platform
            - classpath:/configurations/services

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false